import type {Metadata} from 'next';
import {api} from '../../lib/api';
import {absoluteUrl,jsonLd,SITE_URL} from '../../lib/site';
import InquiryForm from '../../components/InquiryForm';

export const metadata:Metadata={title:'Services',description:'Work with Kraviona on product development, technical SEO, web performance, backend systems and AI automation.',alternates:{canonical:'/services'},openGraph:{url:'/services',title:'Build and grow with Kraviona'}};

export default async function ServicesPage(){
  let services:any[]=[],settings:any={};try{[services,settings]=await Promise.all([api('/services'),api('/settings')])}catch{}
  const official=settings.officialSiteUrl||'https://www.kraviona.com';
  const schema=[{'@context':'https://schema.org','@type':'CollectionPage','@id':`${SITE_URL}/services#page`,url:absoluteUrl('/services'),name:'Kraviona services',description:settings.servicesDescription,about:{'@id':`${SITE_URL}/#organization`},mainEntity:{'@type':'ItemList',itemListElement:services.map((service,index)=>({'@type':'ListItem',position:index+1,item:{'@type':'Service',name:service.title,description:service.summary,provider:{'@id':`${SITE_URL}/#organization`},url:service.officialUrl||official}}))}},{'@context':'https://schema.org','@type':'ContactPage','@id':`${SITE_URL}/services#contact`,url:`${SITE_URL}/services#contact`,mainEntity:{'@id':`${SITE_URL}/#organization`}}];
  return <>
    <section className="services-hero wrap"><div><span className="eyebrow">Strategy · Engineering · Growth</span><h1>{settings.servicesTitle||'From ideas to measurable outcomes.'}</h1><p className="lead">{settings.servicesDescription||'Kraviona Tech Solutions helps teams build faster products, stronger search visibility, and practical AI workflows.'}</p><div className="services-hero__actions"><a className="button" href="#contact">Discuss your project →</a><a className="button button--outline" href={`${official}/services`} target="_blank" rel="noopener noreferrer">View official company site ↗</a></div></div><aside><span>Official service partner</span><strong>Kraviona Tech Solutions</strong><p>This journal is published by Kraviona. Commercial services, company information and direct consultation are available on our official website.</p><a href={official} target="_blank" rel="noopener noreferrer">Visit kraviona.com ↗</a></aside></section>
    <section className="services-list wrap" aria-labelledby="services-title"><div className="section-heading"><div><div className="eyebrow">How we can help</div><h2 id="services-title">Focused expertise. Clear delivery.</h2></div><p>Start with the business outcome. We will recommend the smallest dependable solution that gets you there.</p></div><div className="service-grid">{services.map((service,index)=><article className="service-card" key={service._id}><div className="service-card__number">{String(index+1).padStart(2,'0')}</div><span className="eyebrow">{service.eyebrow}</span><h3>{service.title}</h3><p>{service.summary}</p><ul>{service.deliverables?.map((item:string)=><li key={item}>{item}</li>)}</ul><a href="#contact">Start a conversation →</a><a className="service-card__official" href={service.officialUrl||`${official}/services`} target="_blank" rel="noopener noreferrer">Full service details on kraviona.com ↗</a></article>)}</div></section>
    <section className="contact-section" id="contact"><div className="wrap contact-layout"><div><span className="eyebrow">Start a project</span><h2>Tell us what better looks like.</h2><p>Share a short brief and the team will respond with relevant questions, a practical next step, and an honest view of scope.</p><div className="direct-contact"><a href={`mailto:${settings.contactEmail||'kravionatech@gmail.com'}`}>{settings.contactEmail||'kravionatech@gmail.com'}</a><a href={settings.whatsappUrl||'https://wa.me/919608553167'} target="_blank" rel="noopener noreferrer">WhatsApp {settings.contactPhone||'+91 96085 53167'} ↗</a></div></div><InquiryForm services={services}/></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(schema)}}/>
  </>;
}
