import type { Metadata } from 'next';
import EditorAccountForm from '../../components/EditorAccountForm';

export const metadata: Metadata = { title: 'Guest Posting Opportunities', description: 'Submit original technology, AI, web development, and growth articles to Kraviona. Review our guest posting guidelines and backlink policy.', alternates: { canonical: '/guest-posting' } };

export default function GuestPosting() {
  const editorUrl = process.env.NEXT_PUBLIC_EDITOR_URL || (process.env.NODE_ENV === 'development' ? 'http://localhost:3002' : 'https://editor.kraviona.site');
  return <><section className="guest-hero"><div className="wrap"><div className="eyebrow">Contribute to Kraviona</div><h1>Guest posting for people with useful ideas.</h1><p>Publish useful, original articles on technology, AI, web development, cybersecurity, blockchain, SEO, and modern business.</p><a className="header-cta" href={editorUrl}>Editor login <span>→</span></a></div></section><section className="wrap guest-grid"><article><h2>What we look for</h2><ul><li>Original, accurate articles with a clear takeaway.</li><li>At least 600 words; 1,000–1,800 words is usually ideal.</li><li>Helpful headings, examples, and sources where relevant.</li><li>A topic that fits Kraviona’s technology and growth audience.</li></ul><h2>Backlink policy</h2><ul><li>Your backlink allowance is set by the administrator and counted automatically from article links.</li><li>No keyword stuffing, link exchanges, paid-link guarantees, or promotional copy.</li><li>Links to gambling, adult, illegal, deceptive, or low-quality sites are not accepted.</li><li>We may remove links or apply <code>rel="nofollow sponsored"</code> when appropriate.</li></ul></article><aside className="guest-card"><span className="eyebrow">How it works</span><ol><li>Create an editor account below.</li><li>Wait for Kraviona to approve it and set your link allowance.</li><li>Write and submit only your own articles in the editor portal.</li><li>Our team reviews, edits, and publishes approved work.</li></ol><a className="text-link" href={editorUrl}>Go to editor login →</a></aside></section><section className="wrap guest-account"><EditorAccountForm /></section><section className="wrap guest-note"><h2>Guest posting is editorial, not advertising.</h2><p>Submission does not guarantee publication. By submitting, you confirm that you own the work and give Kraviona permission to edit and publish it.</p></section></>;
}
