#!/usr/bin/env node
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { api } from './api.js';

const server = new McpServer({ name: 'kraviona-cms', version: '1.0.0' });
const result = data => ({ content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] });
const failure = error => ({ content: [{ type: 'text', text: error instanceof Error ? error.message : String(error) }], isError: true });
const tool = (name, config, handler) => server.registerTool(name, config, async args => { try { return result(await handler(args)); } catch (error) { return failure(error); } });

tool('cms_health', { title: 'Kraviona CMS health', description: 'Check whether the Kraviona backend API is online.', inputSchema: z.object({}), annotations: { readOnlyHint: true } }, () => api.health());
tool('list_posts', { title: 'List Kraviona posts', description: 'List editorial posts, optionally filtered by status or search query.', inputSchema: z.object({ status: z.enum(['all','published','draft']).default('all'), search: z.string().optional(), limit: z.number().int().min(1).max(100).default(20) }), annotations: { readOnlyHint: true } }, ({status,search,limit}) => api.request(`/posts?status=all&filter=${status==='all'?'':status}&limit=${limit}&search=${encodeURIComponent(search||'')}`));
tool('get_post', { title: 'Get complete post', description: 'Fetch every editable field for a post by MongoDB ID.', inputSchema: z.object({ id: z.string().min(1) }), annotations: { readOnlyHint: true } }, ({id}) => api.request(`/posts/id/${id}`));

const postFields = { title:z.string().min(3), slug:z.string().optional(), status:z.enum(['draft','published']).default('draft'), content:z.string().min(1), quickAnswer:z.string().max(240).optional(), category:z.string().optional(), tags:z.array(z.string()).optional(), keyTakeaways:z.array(z.string()).optional(), faqs:z.array(z.object({question:z.string(),answer:z.string()})).optional(), featuredImage:z.object({url:z.string().url().or(z.literal('')),alt:z.string()}).optional(), author:z.object({name:z.string(),slug:z.string(),sameAs:z.array(z.string().url())}).optional(), seo:z.object({metaTitle:z.string().max(60).optional(),metaDescription:z.string().max(160).optional(),ogImage:z.string().url().or(z.literal('')).optional(),isNoIndex:z.boolean().optional()}).optional() };
tool('create_post', { title: 'Create editorial post', description: 'Create a complete Kraviona story. Prefer draft status until a human has reviewed facts and SEO.', inputSchema: z.object(postFields), annotations: { idempotentHint: false } }, payload => api.request('/posts',{method:'POST',body:JSON.stringify(payload)}));
tool('update_post', { title: 'Update editorial post', description: 'Update a post by ID. Fetch it first with get_post when making substantial changes.', inputSchema: z.object({ id:z.string(), ...Object.fromEntries(Object.entries(postFields).map(([k,v])=>[k,v.optional()])) }), annotations: { idempotentHint: true } }, ({id,...payload}) => api.request(`/posts/${id}`,{method:'PUT',body:JSON.stringify(payload)}));
tool('set_post_status', { title: 'Publish or unpublish post', description: 'Change a post between draft and published. Publishing automatically enforces indexability, date, canonical URL and word count.', inputSchema: z.object({ id:z.string(), status:z.enum(['draft','published']) }), annotations: { idempotentHint: true } }, ({id,status}) => api.request(`/posts/${id}`,{method:'PUT',body:JSON.stringify({status})}));
tool('delete_post', { title: 'Delete post', description: 'Permanently delete a post. The confirm flag must explicitly be true.', inputSchema: z.object({id:z.string(),confirm:z.literal(true)}), annotations: { destructiveHint:true,idempotentHint:true } }, ({id}) => api.request(`/posts/${id}`,{method:'DELETE'}));

tool('list_categories', { title: 'List categories', description: 'List all dynamic frontend categories and SEO data.', inputSchema: z.object({}), annotations: { readOnlyHint:true } }, () => api.request('/categories',{},false));
tool('save_category', { title: 'Create or update category', description: 'Create or update a category used by frontend navigation and landing pages.', inputSchema: z.object({id:z.string().optional(),name:z.string().min(2),slug:z.string().optional(),description:z.string().optional(),seo:z.object({metaTitle:z.string().max(60).optional(),metaDescription:z.string().max(160).optional()}).optional()}) }, ({id,...payload}) => api.request(id?`/categories/${id}`:'/categories',{method:id?'PUT':'POST',body:JSON.stringify(payload)}));
tool('delete_category', { title: 'Delete empty category', description: 'Delete a category only when it contains no posts.', inputSchema: z.object({id:z.string(),confirm:z.literal(true)}), annotations:{destructiveHint:true,idempotentHint:true} }, ({id}) => api.request(`/categories/${id}`,{method:'DELETE'}));

tool('list_services', { title: 'List Kraviona services', description: 'List the dynamic commercial services displayed on the public frontend.', inputSchema:z.object({status:z.enum(['all','published']).default('all')}),annotations:{readOnlyHint:true} }, ({status}) => api.request(`/services${status==='all'?'?status=all':''}`,{},status==='all'));
tool('save_service', { title: 'Create or update service', description: 'Manage a service, its deliverables, official kraviona.com URL, publishing status and homepage feature flag.', inputSchema:z.object({id:z.string().optional(),title:z.string().min(2),slug:z.string().optional(),eyebrow:z.string().optional(),summary:z.string().min(10).max(320),deliverables:z.array(z.string()).optional(),status:z.enum(['draft','published']).default('draft'),featured:z.boolean().default(false),order:z.number().int().default(0),officialUrl:z.string().url().optional(),seo:z.object({metaTitle:z.string().max(60).optional(),metaDescription:z.string().max(160).optional()}).optional()}) }, ({id,...payload}) => api.request(id?`/services/${id}`:'/services',{method:id?'PUT':'POST',body:JSON.stringify(payload)}));
tool('delete_service', { title:'Delete unused service',description:'Permanently delete a service only if it has no associated client enquiries.',inputSchema:z.object({id:z.string(),confirm:z.literal(true)}),annotations:{destructiveHint:true,idempotentHint:true} }, ({id})=>api.request(`/services/${id}`,{method:'DELETE'}));
tool('list_inquiries', { title:'List client enquiries',description:'Read project briefs submitted from the public services contact form.',inputSchema:z.object({status:z.enum(['all','new','contacted','qualified','closed','spam']).default('all')}),annotations:{readOnlyHint:true} }, ({status})=>api.request(`/inquiries?status=${status}`));
tool('update_inquiry', { title:'Update client enquiry',description:'Set the sales follow-up status and private admin notes for a client enquiry.',inputSchema:z.object({id:z.string(),status:z.enum(['new','contacted','qualified','closed','spam']),notes:z.string().max(4000).optional()}) }, ({id,...payload})=>api.request(`/inquiries/${id}`,{method:'PATCH',body:JSON.stringify(payload)}));

tool('get_site_settings', { title: 'Get website settings', description: 'Read global branding, homepage content, newsletter copy, default SEO and social profiles.', inputSchema:z.object({}), annotations:{readOnlyHint:true} }, () => api.request('/settings',{},false));
tool('update_site_settings', { title: 'Update website settings', description: 'Update global content, official company link, contact details and SEO displayed dynamically on the public frontend.', inputSchema:z.object({brandName:z.string().optional(),tagline:z.string().optional(),heroEyebrow:z.string().optional(),heroTitle:z.string().optional(),heroDescription:z.string().optional(),briefingTitle:z.string().optional(),briefingDescription:z.string().optional(),officialSiteUrl:z.string().url().optional(),contactEmail:z.string().email().optional(),contactPhone:z.string().optional(),whatsappUrl:z.string().url().optional(),servicesTitle:z.string().optional(),servicesDescription:z.string().optional(),defaultSeo:z.object({title:z.string().max(60).optional(),description:z.string().max(160).optional(),ogImage:z.string().url().or(z.literal('')).optional()}).optional(),socialLinks:z.array(z.object({label:z.string(),url:z.string().url()})).optional()}),annotations:{idempotentHint:true} }, payload => api.request('/settings',{method:'PUT',body:JSON.stringify(payload)}));
tool('generate_ai_draft', { title: 'Generate AI draft', description: 'Ask the configured Anthropic model to create a complete SEO draft for human review.', inputSchema:z.object({topic:z.string().min(5),category:z.string().min(1)}) }, payload => api.request('/ai-agent/generate',{method:'POST',body:JSON.stringify(payload)}));
tool('list_keyword_queue', { title: 'List automation queue', description: 'List pending and used keywords for automated content generation.', inputSchema:z.object({}),annotations:{readOnlyHint:true} }, () => api.request('/keyword-queue'));
tool('add_keyword', { title: 'Add keyword to automation queue', description: 'Add a keyword and target category to the automatic generation queue.', inputSchema:z.object({keyword:z.string().min(2),targetCategory:z.string().min(1),priority:z.number().int().default(0)}) }, payload => api.request('/keyword-queue',{method:'POST',body:JSON.stringify(payload)}));

const transport = new StdioServerTransport();
await server.connect(transport);
process.on('SIGINT', async () => { await server.close(); process.exit(0); });
